ObsUygulaması/Controllers/DersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ObsUygulaması.Models;

namespace ObsUygulaması.Controllers
{
    public class DersController : Controller
    {
        private obssaEntities db = new obssaEntities();

        // GET: Ders
        public ActionResult Index()
        {
            var ders = db.Ders.Include(d => d.Ogrenci);
            return View(ders.ToList());
        }

        // GET: Ders/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ders ders = db.Ders.Find(id);
            if (ders == null)
            {
                return HttpNotFound();
            }
            return View(ders);
        }

        // GET: Ders/Create
        public ActionResult Create()
        {
            ViewBag.OgrId = new SelectList(db.Ogrenci, "Id", "AdSoyad");
            return View();
        }

        // POST: Ders/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,DersAdı,OgrId")] Ders ders)
        {
            if (ModelState.IsValid)
            {
                db.Ders.Add(ders);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.OgrId = new SelectList(db.Ogrenci, "Id", "AdSoyad", ders.OgrId);
            return View(ders);
        }

        // GET: Ders/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ders ders = db.Ders.Find(id);
            if (ders == null)
            {
                return HttpNotFound();
            }
            ViewBag.OgrId = new SelectList(db.Ogrenci, "Id", "AdSoyad", ders.OgrId);
            return View(ders);
        }

        // POST: Ders/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,DersAdı,OgrId")] Ders ders)
        {
            if (ModelState.IsValid)
            {
                db.Entry(ders).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.OgrId = new SelectList(db.Ogrenci, "Id", "AdSoyad", ders.OgrId);
            return View(ders);
        }

        // GET: Ders/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ders ders = db.Ders.Find(id);
            if (ders == null)
            {
                return HttpNotFound();
            }
            return View(ders);
        }

        // POST: Ders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Ders ders = db.Ders.Find(id);
            db.Ders.Remove(ders);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ObsUygulaması/Controllers/LoginController.cs
using ObsUygulaması.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ObsUygulaması.Controllers
{
    public class LoginController : Controller
    {
        private obssaEntities db = new obssaEntities();
        // GET: Login
        public ActionResult AdminLogin()
        {
            return View();
        }
        public ActionResult StudentLogin()
        {
            return View();
        }
        public ActionResult AnaGiris()
        {
            return View();
        }
       

        

        [HttpPost]
        public ActionResult AdminLogin(string username, string password)
        {
            using (var context = new obssaEntities())
            {
                var student = context.Admin.FirstOrDefault(s => s.Username == username && s.Password == password);
                if (student != null)
                {
                    Session["OgrenciNo"] = username;

                    return RedirectToAction("AdminInfo", "Home");
                }
                else
                {
                    return RedirectToAction("AnaGiris", "Home");
                }
            }

            //Kullanıcı bulunamadı veya şifre geçersiz, hata mesajı gösterme
            ViewBag.ErrorMessage = "Kullanıcı bulunamadı veya şifre geçersiz. Lütfen doğru ad ve soyad giriniz.";
            return View();
        }

        [HttpPost]
        public ActionResult StudentLogin(string OgrNo, string password)
        {
            using (var context = new obssaEntities())
            {
                var student = context.Ogrenci.FirstOrDefault(s => s.No == OgrNo && s.Sifre == password);
                if (student != null)
                {
                    Session["OgrenciNo"] = OgrNo;

                    return RedirectToAction("OgrenciGiris", "Home");
                }
                else
                {
                    return RedirectToAction("AnaGiris", "Home");
                }
            }

            //Kullanıcı bulunamadı veya şifre geçersiz, hata mesajı gösterme
            ViewBag.ErrorMessage = "Kullanıcı bulunamadı veya şifre geçersiz. Lütfen doğru ad ve soyad giriniz.";
            return View();
        }

       
        

    }
}

ObsUygulaması/Controllers/NotsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ObsUygulaması.Models;

namespace ObsUygulaması.Controllers
{
    public class NotsController : Controller
    {
        private obssaEntities db = new obssaEntities();

        // GET: Nots
        public ActionResult Index()
        {
            var not = db.Not.Include(n => n.Ders).Include(n => n.Ogrenci);
            return View(not.ToList());
        }

        // GET: Nots/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Not not = db.Not.Find(id);
            if (not == null)
            {
                return HttpNotFound();
            }
            return View(not);
        }

        // GET: Nots/Create
        public ActionResult Create()
        {
            ViewBag.DersId = new SelectList(db.Ders, "Id", "DersAdı");
            ViewBag.OgrId = new SelectList(db.Ogrenci, "Id", "AdSoyad");
            ViewBag.OgrenciId = new SelectList(db.Ogrenci, "Id", "No");

            return View();
        }

        // POST: Nots/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Vize1,Vize2,Final,GeçtiMiKaldiMi,OgrId,DersId,OgrenciId")] Not not)
        {
            if (ModelState.IsValid)
            {
                db.Not.Add(not);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.DersId = new SelectList(db.Ders, "Id", "DersAdı", not.DersId);
            ViewBag.OgrId = new SelectList(db.Ogrenci, "Id", "AdSoyad", not.OgrId);
            ViewBag.OgrenciId = new SelectList(db.Ogrenci, "Id", "No",not.Ogrenci);
            return View(not);
        }

        // GET: Nots/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Not not = db.Not.Find(id);
            if (not == null)
            {
                return HttpNotFound();
            }
            ViewBag.DersId = new SelectList(db.Ders, "Id", "DersAdı", not.DersId);
            ViewBag.OgrId = new SelectList(db.Ogrenci, "Id", "AdSoyad");
            ViewBag.OgrenciId = new SelectList(db.Ogrenci, "Id", "No");
            return View(not);
        }

        // POST: Nots/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Vize1,Vize2,Final,GeçtiMiKaldiMi,OgrId,DersId,OgrenciId")] Not not)
        {
            if (ModelState.IsValid)
            {
                db.Entry(not).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.DersId = new SelectList(db.Ders, "Id", "DersAdı", not.DersId);
            ViewBag.OgrId = new SelectList(db.Ogrenci, "Id", "AdSoyad", not.OgrId);
            return View(not);
        }

        // GET: Nots/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Not not = db.Not.Find(id);
            if (not == null)
            {
                return HttpNotFound();
            }
            return View(not);
        }

        // POST: Nots/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Not not = db.Not.Find(id);
            db.Not.Remove(not);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ObsUygulaması/Controllers/OgrencisController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ObsUygulaması.Models;

namespace ObsUygulaması.Views
{
    public class OgrencisController : Controller
    {
        private obssaEntities db = new obssaEntities();

        [HttpGet]
        public JsonResult GetOgrenciAdSoyad(int id)
        {
            var ogrenci = db.Ogrenci.FirstOrDefault(o => o.Id == id);
            if (ogrenci != null)
            {
                return Json(ogrenci.AdSoyad, JsonRequestBehavior.AllowGet);
            }
            return Json(null, JsonRequestBehavior.AllowGet);
        }

        // GET: Ogrencis
        public ActionResult Index()
        {
            return View(db.Ogrenci.ToList());
        }

        // GET: Ogrencis/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ogrenci ogrenci = db.Ogrenci.Find(id);
            if (ogrenci == null)
            {
                return HttpNotFound();
            }
            return View(ogrenci);
        }

        // GET: Ogrencis/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Ogrencis/Create
       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,AdSoyad,No,Bolum,Mail,Tel,Address,Sifre")] Ogrenci ogrenci)
        {
            if (ModelState.IsValid)
            {
                db.Ogrenci.Add(ogrenci);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(ogrenci);
        }

        // GET: Ogrencis/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ogrenci ogrenci = db.Ogrenci.Find(id);
            if (ogrenci == null)
            {
                return HttpNotFound();
            }
            return View(ogrenci);
        }

        // POST: Ogrencis/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,AdSoyad,No,Bolum,Mail,Tel,Address,Sifre")] Ogrenci ogrenci)
        {
            if (ModelState.IsValid)
            {
                db.Entry(ogrenci).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(ogrenci);
        }

        // GET: Ogrencis/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ogrenci ogrenci = db.Ogrenci.Find(id);
            if (ogrenci == null)
            {
                return HttpNotFound();
            }
            return View(ogrenci);
        }

        // POST: Ogrencis/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Ogrenci ogrenci = db.Ogrenci.Find(id);
            db.Ogrenci.Remove(ogrenci);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ObsUygulaması/Views/Home/AnaGiris.cshtml
@{
    ViewBag.Title = "Ana Giris";
}

<h2>Ana Giris</h2>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
    <title>Trakya Üniversitesi Öğrenci Otomasyonu</title>
</head>
<body>
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-7 p-6 bg-warning text-white">
                <img src="/Web/img/trakya-universitesi-logo.png" class="img-fluid" alt="Trakya Üniversitesi">

            </div>

            <div class="col-sm-5 p-6 bg-dark text-white">
                <br><br><br><br><br>
                <h1 class="mt-4"><center>Trakya Üniversitesi Öğrenci Otomasyonu</center></h1>
                <h2 class="mt-5"><center>Öğrenci Girişi</center></h2>
                <div class="row">
                    <div class="col-sm-3"></div>
                    <div class="col-sm-6">
                        <form action="@Url.Action("StudentLogin", "Login")" method="post">
                            @using (Html.BeginForm("StudentLogin", "Login", FormMethod.Post))
                            {
                                <div class="mb-3 mt-3">
                                    <label for="ogrencino" class="form-label">Öğrenci No : </label>
                                    <input type="text" class="form-control " id="ogrencino" name="OgrNo">
                                </div>
                                <div class="mb-3">
                                    <label for="sifre" class="form-label">Şifre : </label>
                                    <input type="password" class="form-control" id="sifre" name="password">
                                </div>
                                <div class="form-check mb-3">
                                    <label class="form-check-label">
                                        <input class="form-check-input" type="checkbox" name="remember"> Beni Hatırla
                                    </label>
                                </div>
                                <button type="submit" class="btn btn-primary">Giriş</button>
                            }
                        </form>
                        <h2 class="mt-5"><center>Yönetici Girişi</center></h2>

                        <form action="@Url.Action("AdminLogin", "Login")" method="post">
                            @using (Html.BeginForm("AdminLogin", "Login", FormMethod.Post))
                            {
                                <div class="mb-3 mt-3">
                                    <label for="ogrencino" class="form-label">Username : </label>
                                    <input type="text" class="form-control " id="ogrencino" name="username">
                                </div>
                                <div class="mb-3">
                                    <label for="sifre" class="form-label">Şifre : </label>
                                    <input type="password" class="form-control" id="sifre" name="password">
                                </div>
                                <div class="form-check mb-3">
                                    <label class="form-check-label">
                                        <input class="form-check-input" type="checkbox" name="remember"> Beni Hatırla
                                    </label>
                                </div>
                                <button type="submit" class="btn btn-primary">Giriş</button>
                            }
                        </form>
                    </div>
                    <div class="col-sm-3"></div>

                </div>


            </div>

        </div>
    </div>

</body>
</html>

ObsUygulaması/Views/Home/DersEkle.cshtml
@model ObsUygulaması.Models.Ders

@{
    ViewBag.Title = "Ders Oluştur";
}

<h4>Ders Oluştur</h4>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.DersAdı, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DersAdı, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DersAdı, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OgrId, "OgrId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("OgrId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.OgrId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Oluştur" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Önceki Sayfa", "AdminInfo")
</div>

ObsUygulaması/Views/Home/DersListele.cshtml
@model IEnumerable<ObsUygulaması.Models.Ders>

@{
    ViewBag.Title = "Ders Listele";
}

<h2>Ders Listele</h2>

<p>
    @Html.ActionLink("Yeni Ders Oluştur", "Create", "Ders")
</p>
<table class="table">
    <tr>
        <th>
            Ders Adı :
        </th>
        <th>
            Öğrenci Ad Soyad :
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.DersAdı)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Ogrenci.AdSoyad)
            </td>
            <td>
                @Html.ActionLink("Düzenle", "Edit", "Ders", new { id = item.Id }, null) |
                @Html.ActionLink("Detay", "Details", "Ders", new { id = item.Id }, null)  |
                @Html.ActionLink("Sil", "Delete", "Ders", new { id = item.Id }, null)
            </td>
        </tr>
    }

</table>
<div>
    @Html.ActionLink("Önceki Sayfa", "AdminInfo")
</div>

ObsUygulaması/Views/Home/NotListele.cshtml
@model IEnumerable<ObsUygulaması.Models.Not>

@{
    ViewBag.Title = "Not Listele";
}

<h2>Not Listele</h2>

<p>
    @Html.ActionLink("Yeni Not Oluştur", "Create", "Nots")
</p>
<table class="table">
    <tr>
        <th>
            Vize 1 :
        </th>
        <th>
            Vize 2 :
        </th>
        <th>
            Final :
        </th>
        <th>
            Geçti / Kaldı :
        </th>
        <th>
            Ders Adı :
        </th>
        <th>
            Öğrenci Ad Soyad :
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Vize1)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Vize2)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Final)
            </td>
            <td>
                @if (item.GeçtiMiKaldiMi.HasValue)
                {
                    if (item.GeçtiMiKaldiMi.Value)
                    {
                        <text>Geçti</text>
                    }
                    else
                    {
                        <text>Kaldı</text>
                    }
                }
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Ders.DersAdı)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Ogrenci.AdSoyad)
            </td>
            <td>
                @Html.ActionLink("Düzenle", "Edit", "Nots", new { id = item.Id }, null)  |
                @Html.ActionLink("Detay", "Details", "Nots", new { id = item.Id }, null)  |
                @Html.ActionLink("Sil", "Delete", "Nots", new { id = item.Id }, null)
            </td>
        </tr>
    }

</table>
<div>
    @Html.ActionLink("Önceki Sayfa", "AdminInfo")
</div>

ObsUygulaması/Views/Home/OgrenciBilgileri.cshtml
@model ObsUygulaması.Models.Ogrenci
@{
    ViewBag.Title = "Öğrenci Bilgileri";
}

<h2>Öğrenci Bilgileri</h2>


<div>
    <hr />
    <dl class="dl-horizontal">

        @if (Model != null)
        {
            <p>Öğrenci Adı Soyadı : @Html.DisplayFor(model => model.AdSoyad)</p>
            <p>Öğrenci Numarası : @Html.DisplayFor(model => model.No)</p>
            <p>Öğrenci Id : @Html.DisplayFor(model => model.Id)</p>
            <p>Öğrenci Telefon : @Html.DisplayFor(model => model.Tel)</p>
            <p>Öğrenci Adres : @Html.DisplayFor(model => model.Address)</p>
            <p>Öğrenci Bölümü : @Html.DisplayFor(model => model.Bolum)</p>
            <p>Öğrenci Mail Adresi : @Html.DisplayFor(model => model.Mail)</p>



        }
        else
        {
            <p> Öğrenci bilgileri bulunamadı.</p>
        }
        
    </dl>
</div>
<div>
    @Html.ActionLink("Önceki Sayfa", "OgrenciGiris")
</div>

ObsUygulaması/Views/Home/OgrenciListele.cshtml
@model IEnumerable<ObsUygulaması.Models.Ogrenci>

@{
    ViewBag.Title = "Öğrenci Listele";
}

<h2>Öğrenci Listele</h2>

<p>
    @Html.ActionLink("Create New", "Create", "Ogrencis")
</p>
<table class="table">
    <tr>
        <th>
            Ad Soyad :
        </th>
        <th>
            Öğrenci Numarası :
        </th>
        <th>
            Bölümü :
        </th>
        <th>
            Mail Adresi :
        </th>
        <th>
            Telefon Numarası :
        </th>
        <th>
            Adres :
        </th>
        <th>
            Şifre :
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.AdSoyad)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.No)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Bolum)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Mail)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Tel)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Address)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Sifre)
    </td>
    <td>
        @Html.ActionLink("Düzenle", "Edit", "Ogrencis", new { id = item.Id }, null) |
        @Html.ActionLink("Detay", "Details", "Ogrencis", new { id = item.Id }, null) |
        @Html.ActionLink("Sil", "Delete", "Ogrencis", new { id = item.Id }, null)
    </td>
</tr>
    }

</table>
<div>
    @Html.ActionLink("Önceki Sayfa", "AdminInfo")
</div>

ObsUygulaması/Views/Home/YeniKayıt.cshtml
<!doctype html>
<html>

<head>
    <meta charset="utf-8">
    <title>Öğrenci Otomasyonu</title>


    <meta name="viewport" content="width=device-width, initial-scale=1.0">


    <link href='https://fonts.googleapis.com/css?family=Fjalla+One' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,400italic' rel='stylesheet' type='text/css'>



    <link rel="stylesheet" type="text/css" href="/Web/ogretmen/css/grid.css">
    <link rel="stylesheet" type="text/css" href="/Web/ogretmen/css/style.css">
    <link rel="stylesheet" type="text/css" href="/Web/ogretmen/css/animate.css">
    <link rel="stylesheet" type="text/css" href="/Web/ogretmen/css/responsive.css">


</head>

<body>


    <div class="wrapper" id="about">

        <div class="container">
            <section class="team clearfix">
                <div class="row">

                    <div class="team-title">
                        <h3>ÖĞRENCİ OLUŞTUR</h3>

                        <span></span>
                    </div>


                    @*<form>
                            <div>
                                <label for="ogrenciAdi">Öğrenci Adı Soyadı :</label>
                                <input type="text" id="ogrenciAdi" name="AdSoyad">
                            </div>
                            <div>
                                <label for="ogrenciSoyadi">Öğrenci Numarası</label>
                                <input type="text" id="ogrenciSoyadi" name="No">
                            </div>
                            <div>
                                <button @Html.ActionLink("Create", "Ogrencis") type="submit">Gönder</button>
                            </div>
                        </form>*@





                    @*<center>
                            <form action="/Ogrencis/Create" method="post">
                                @using (Html.BeginForm("Create","Ogrencis", FormMethod.Post)) {
                            <div class="text os-animation"><input type="text" placeholder="Öğrenci Adı Soyadı" /></div>
                                <div class="number os-animation"><input type="number" placeholder="Öğrenci Numarası" /></div>
                                <div class="text os-animation"><input type="text" placeholder="Bölüm" /></div>
                                <div class="email os-animation"><input type="email" placeholder="Öğrenci Mail Adresi" /></div>
                                <div class="number os-animation"><input type="number" placeholder="Telefon Numarası" /></div>
                                <div class="text os-animation"><input type="text" placeholder="Adres" /></div>
                                <div class="text os-animation"><input type="password" placeholder="Şifre" /></div>
                                <div>
                                    <button type="submit">Gönder</button>
                                </div>
                            </form>
                        </center>*@
                </div>

            </section>

        </div>
    </div>
    <div>
        @Html.ActionLink("Önceki Sayfa", "AdminInfo")
    </div>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="/Web/ogretmen/js/waypoints.min.js"></script>
    <script src="/Web/ogretmen/js/jquery.bxslider.js"></script>
    <script src="/Web/ogretmen/js/main.js"></script>
    <script src="/Web/ogretmen/js/scripts.js"></script>
    <script src="/Web/ogretmen/js/placeholders.min.js"></script>

    <script type="text/javascript">
        $(window).scroll(function () {
            if ($(this).scrollTop() > 1) {
                $('#sticky1').addClass("sticky");
            }
            else {
                $('#sticky1').removeClass("sticky");
            }
        });
    </script>
</body>

</html>