ObsUygulaması/Models/Duyuru.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ObsUygulaması.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Duyuru
    {
        public int Id { get; set; }
        public string Baslik { get; set; }
        public string Icerik { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
    }
}

ObsUygulaması/Controllers/DuyurusController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace ObsUygulaması.Models
{
    public class DuyurusController : Controller
    {
        private obssaEntities db = new obssaEntities();

        // GET: Duyurus
        public ActionResult Index()
        {
            return View(db.Duyuru.ToList());
        }

        // GET: Duyurus/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Duyuru duyuru = db.Duyuru.Find(id);
            if (duyuru == null)
            {
                return HttpNotFound();
            }
            return View(duyuru);
        }

        // GET: Duyurus/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Duyurus/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Baslik,Icerik,Tarih")] Duyuru duyuru)
        {
            if (ModelState.IsValid)
            {
                duyuru.Tarih = DateTime.Now;
                db.Duyuru.Add(duyuru);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(duyuru);
        }

        // GET: Duyurus/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Duyuru duyuru = db.Duyuru.Find(id);
            if (duyuru == null)
            {
                return HttpNotFound();
            }
            return View(duyuru);
        }

        // POST: Duyurus/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Baslik,Icerik,Tarih")] Duyuru duyuru)
        {
            if (ModelState.IsValid)
            {
                db.Entry(duyuru).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(duyuru);
        }

        // GET: Duyurus/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Duyuru duyuru = db.Duyuru.Find(id);
            if (duyuru == null)
            {
                return HttpNotFound();
            }
            return View(duyuru);
        }

        // POST: Duyurus/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Duyuru duyuru = db.Duyuru.Find(id);
            db.Duyuru.Remove(duyuru);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ObsUygulaması/Views/Duyurus/Create.cshtml
@model ObsUygulaması.Models.Duyuru

@{
    ViewBag.Title = "Duyuru Oluştur";
}

<h2>Duyuru Oluştur</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Baslik,"Duyuru Adı : ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Baslik, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Baslik, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Icerik,"Açıklama : ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Icerik, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Icerik, "", new { @class = "text-danger" })
            </div>
        </div>

        @Html.HiddenFor(model => model.Tarih)


        @* <div class="form-group">
                @Html.LabelFor(model => model.Tarih, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Tarih, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Tarih, "", new { @class = "text-danger" })
                </div>
            </div>*@

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Oluştur" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Önceki Sayfa", "Index")
</div>

ObsUygulaması/Views/Duyurus/Delete.cshtml
@model ObsUygulaması.Models.Duyuru

@{
    ViewBag.Title = "Duyuru Sil";
}

<h2>Duyuru sil</h2>

<h3>Bunu silmek istediğinizden emin misiniz?</h3>
<div>

    <hr />
    <dl class="dl-horizontal">
        <dt>
            Duyuru Adı :
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Baslik)
        </dd>

        <dt>
            Açıklama :
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Icerik)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tarih)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tarih)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Sil" class="btn btn-default" /> |
            @Html.ActionLink("Önceki Sayfa", "Index")
        </div>
    }
</div>

ObsUygulaması/Views/Duyurus/Details.cshtml
@model ObsUygulaması.Models.Duyuru

@{
    ViewBag.Title = "Duyuru Detay";
}


<h2>Duyuru Detay</h2>

<div>

    <hr />
    <dl class="dl-horizontal">
        <dt>
            Duyuru Adı :
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Baslik)
        </dd>

        <dt>
            Açıklama :
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Icerik)
        </dd>

        <dt>
            Tarih :
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tarih)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Düzenle", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Önceki Sayfa", "Index")
</p>

ObsUygulaması/Views/Duyurus/Edit.cshtml
@model ObsUygulaması.Models.Duyuru

@{
    ViewBag.Title = "Duyuru Düzenle";
}


<h2>Duyuru Düzenle</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Baslik, "Duyuru Adı : ", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Baslik, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Baslik, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Icerik, "Açıklama : ", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Icerik, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Icerik, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Tarih,"Tarih : ", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Tarih, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Tarih, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Kaydet" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Önceki Sayfa", "Index")
</div>

ObsUygulaması/Views/Duyurus/Index.cshtml
@model IEnumerable<ObsUygulaması.Models.Duyuru>

@{
    ViewBag.Title = "Duyurular";
}

<h2>Duyurular</h2>

<p>
    @Html.ActionLink("Yeni Duyuru Oluştur", "Create")
</p>
<table class="table">
    <tr>
        <th>
            Duyuru Adı :
        </th>
        <th>
            Açıklama :
        </th>
        <th>
            Tarih :
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Baslik)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Icerik)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Tarih)
            </td>
            <td>
                @Html.ActionLink("Düzenle", "Edit", "Duyurus",new { id = item.Id }, null) |
                @Html.ActionLink("Detay", "Details", "Duyurus", new { id = item.Id }, null) |
                @Html.ActionLink("Sil", "Delete", "Duyurus", new { id = item.Id }, null)
            </td>
        </tr>
    }

</table>
<div>
    @Html.ActionLink("Önceki Sayfa", "AdminInfo", "Home")
</div>